### ISSUE TITLE
automod rule actions outputs [object, Object], [object, Object] instead of the actions

### ISSUE THREAD

**Issue by 5Dotsu** [5Dotsu/fkz-bot#1]

**Comment by 5Dotsu** [comment]
log: 
```
08.04 20:21:34 [Bot] node:events:491
08.04 20:21:34 [Bot] throw er; // Unhandled 'error' event
08.04 20:21:34 [Bot] ^
08.04 20:21:34 [Bot] TypeError: Cannot read properties of null (reading 'guild')
08.04 20:21:34 [Bot] at Client.<anonymous> (/src/index.js:1018:36)
08.04 20:21:34 [Bot] at Client.emit (node:events:513:28)
08.04 20:21:34 [Bot] at AutoModerationRuleUpdateAction.handle (/node_modules/discord.js/src/client/actions/AutoModerationRuleUpdate.js:22:14)
08.04 20:21:34 [Bot] at Object.module.exports [as AUTO_MODERATION_RULE_UPDATE] (/node_modules/discord.js/src/client/websocket/handlers/AUTO_MODERATION_RULE_UPDATE.js:4:43)
08.04 20:21:34 [Bot] at WebSocketManager.handlePacket (/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
08.04 20:21:34 [Bot] at WebSocketShard.onPacket (/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
08.04 20:21:34 [Bot] at WebSocketShard.onMessage (/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
08.04 20:21:34 [Bot] at callListener (/node_modules/ws/lib/event-target.js:290:14)
08.04 20:21:34 [Bot] at WebSocket.onMessage (/node_modules/ws/lib/event-target.js:209:9)
08.04 20:21:34 [Bot] at WebSocket.emit (node:events:513:28)
08.04 20:21:34 [Bot] Emitted 'error' event on Client instance at:
08.04 20:21:34 [Bot] at emitUnhandledRejectionOrErr (node:events:394:10)
08.04 20:21:34 [Bot] at processTicksAndRejections (node:internal/process/task_queues:85:21)
```

**Comment by 5Dotsu** [comment]
https://github.com/5Dotsu/fkz-bot/commit/a977cbaf97ea8a4ab19f43a65fc3b79fc722c314 crash has been fixed, but actions doesn't output anything smart so it still doesn't work

**Comment by 5Dotsu** [comment]
```
client.on(
  Events.AutoModerationRuleUpdate,
  // 1st param is "param or null" and reads null ????
  async (newAutoModerationRule, oldAutoModerationRule) => {
    const data = await Audit_Log.findOne({
      Guild: newAutoModerationRule.guild.id,
    });
...
```
the 1st parameter of the function always reads "or null" which caused the crash, I'm too stupid to make it not read null so erm yea

**Comment by 5Dotsu** [comment]
```
value: `${oldAutoModerationRule.actions}`
```
outputs [object, Object], [object, Object] idk how to fix lol

**Comment by 5Dotsu** [comment]
happens cuz its an array, but was being treated as a string

**Comment by 5Dotsu** [comment]
https://github.com/5Dotsu/fkz-bot/commit/62ee8744b4c04c17a02a7cf7555bae2e8bd9d360 speculative fix

**Comment by 5Dotsu** [comment]
speculative fix didn't fix
