### ISSUE TITLE
mongoose causes crash when ver>6.9.2

### ISSUE THREAD

**Issue by 5Dotsu** [5Dotsu/fkz-bot#6]
mongodb connection requires updating

crashlog (mongoose v8.3.1):
```
08.04 19:42:05 [Bot] MongoParseError: option keepalive is not supported
08.04 19:42:05 [Bot] at parseOptions (/node_modules/mongodb/lib/connection_string.js:273:15)
08.04 19:42:05 [Bot] at new MongoClient (/node_modules/mongodb/lib/mongo_client.js:52:63)
08.04 19:42:05 [Bot] at NativeConnection.createClient (/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:293:14)
08.04 19:42:05 [Bot] at NativeConnection.openUri (/node_modules/mongoose/lib/connection.js:801:34)
08.04 19:42:05 [Bot] at Mongoose.connect (/node_modules/mongoose/lib/mongoose.js:414:15)
08.04 19:42:05 [Bot] at Object.execute (/src/events/ready.js:14:20)
08.04 19:42:05 [Bot] at Client.<anonymous> (/src/functions/handelEvents.js:6:52)
08.04 19:42:05 [Bot] at Object.onceWrapper (node:events:628:26)
08.04 19:42:05 [Bot] at Client.emit (node:events:525:35)
08.04 19:42:05 [Bot] at WebSocketManager.triggerClientReady (/node_modules/discord.js/src/client/websocket/WebSocketManager.js:385:17)
08.04 19:42:05 [Bot] Emitted 'error' event on Client instance at:
08.04 19:42:05 [Bot] at emitUnhandledRejectionOrErr (node:events:394:10)
08.04 19:42:05 [Bot] at processTicksAndRejections (node:internal/process/task_queues:85:21) {
08.04 19:42:05 [Bot] [Symbol(errorLabels)]: Set(0) {}
08.04 19:42:05 [Bot] } 
```

**Comment by 5Dotsu** [comment]
https://github.com/5Dotsu/fkz-bot/commit/170466a34583367de75c8129388fa52c4c4e1edb fixed
